spawnRegion:
  world: "world"
  xMin: -1936
  zMin: -2304
  xMax: 2447
  zMax: 1474

mobRegions:
  hard:
  - ==: fr.olympa.api.region.ChunkCuboid
    world: "world"
    chunkXMin: -94
    chunkZMin: -144
    chunkXMax: 137
    chunkZMax: 81
  medium: []
  easy: []

hub:
  world: "world"
  xMin: 5400
  zMin: 5300
  xMax: 5710
  zMax: 5700
spawn:
  world: "world"
  x: 5632.5
  y: 5.0
  z: 5632.5
  pitch: 0.0
  yaw: 180.0