name: OlympaZTA
version: @plugin_version@
api-version: 1.16
depend: [OlympaCore, Citizens]
softdepend: [dynmap, BeautyQuests, Sentinel]
authors: [SkytAsul]
main: fr.olympa.zta.OlympaZTA
website: https://gitlab.com/olympa/olympazta