package fr.olympa.zta.shops;

import java.util.Arrays;
import java.util.List;

import org.bukkit.DyeColor;
import org.bukkit.Material;

public class CivilBlockShop extends BlockShop {

	private static final List<Article<Material>> materials = Arrays.asList(
			new Article<>(Material.COBBLESTONE, 10),
			new Article<>(Material.GRANITE, 10),
			new Article<>(Material.DIORITE, 10),
			new Article<>(Material.ANDESITE, 10),
			new Article<>(Material.COBBLESTONE_STAIRS, 10),
			new Article<>(Material.BRICKS, 10),
			new Article<>(Material.BRICK_STAIRS, 10),
			new Article<>(Material.STONE, 15),
			new Article<>(Material.POLISHED_GRANITE, 15),
			new Article<>(Material.POLISHED_DIORITE, 15),
			new Article<>(Material.POLISHED_ANDESITE, 15),
			new Article<>(Material.STONE_STAIRS, 15),
			new Article<>(Material.STONE_BRICKS, 15),
			new Article<>(Material.STONE_BRICK_STAIRS, 15),
			new Article<>(Material.GRASS_BLOCK, 5),
			new Article<>(Material.COARSE_DIRT, 5),
			new Article<>(Material.DIRT, 5),
			new Article<>(Material.SAND, 10),
			new Article<>(Material.RED_SAND, 10),
			new Article<>(Material.OAK_TRAPDOOR, 20),
			new Article<>(Material.OAK_SIGN, 20),
			new Article<>(Material.OAK_LOG, 20),
			new Article<>(Material.OAK_PLANKS, 5),
			new Article<>(Material.CRAFTING_TABLE, 20),
			new Article<>(Material.CHEST, 1000),
			new Article<>(Material.OAK_STAIRS, 5),
			new Article<>(Material.LADDER, 10),
			new Article<>(Material.OAK_DOOR, 20),
			new Article<>(Material.SANDSTONE, 10),
			new Article<>(Material.CUT_SANDSTONE, 10),
			new Article<>(Material.CHISELED_SANDSTONE, 10),
			new Article<>(Material.SMOOTH_SANDSTONE, 10),
			new Article<>(Material.SANDSTONE_STAIRS, 10),
			new Article<>(Material.SANDSTONE_SLAB, 10),
			new Article<>(Material.CUT_SANDSTONE_SLAB, 10),
			new Article<>(Material.RED_SANDSTONE, 10),
			new Article<>(Material.CUT_RED_SANDSTONE, 10),
			new Article<>(Material.CHISELED_RED_SANDSTONE, 10),
			new Article<>(Material.SMOOTH_RED_SANDSTONE, 10),
			new Article<>(Material.RED_SANDSTONE_STAIRS, 10),
			new Article<>(Material.RED_SANDSTONE_SLAB, 10),
			new Article<>(Material.CUT_RED_SANDSTONE_SLAB, 10),
			new Article<>(Material.OAK_SAPLING, 50),
			new Article<>(Material.SPRUCE_SAPLING, 50),
			new Article<>(Material.BIRCH_SAPLING, 50),
			new Article<>(Material.JUNGLE_SAPLING, 50),
			new Article<>(Material.ACACIA_SAPLING, 50),
			new Article<>(Material.DARK_OAK_SAPLING, 50),
			new Article<>(Material.DANDELION, 5),
			new Article<>(Material.POPPY, 5),
			new Article<>(Material.BLUE_ORCHID, 5),
			new Article<>(Material.ALLIUM, 5),
			new Article<>(Material.AZURE_BLUET, 5),
			new Article<>(Material.RED_TULIP, 5),
			new Article<>(Material.ORANGE_TULIP, 5),
			new Article<>(Material.WHITE_TULIP, 5),
			new Article<>(Material.PINK_TULIP, 5),
			new Article<>(Material.OXEYE_DAISY, 5),
			new Article<>(Material.CORNFLOWER, 5),
			new Article<>(Material.LILY_OF_THE_VALLEY, 5),
			new Article<>(Material.ROSE_BUSH, 5),
			new Article<>(Material.PEONY, 5),
			new Article<>(Material.LILAC, 5),
			new Article<>(Material.SUNFLOWER, 5),
			new Article<>(Material.SEAGRASS, 5),
			new Article<>(Material.SEA_PICKLE, 10),
			new Article<>(Material.FLOWER_POT, 5),
			new Article<>(Material.BUCKET, 25),
			new Article<>(Material.WATER_BUCKET, 50),
			new Article<>(Material.VINE, 100),
			new Article<>(Material.CACTUS, 100),
			new Article<>(Material.BAMBOO, 100),
			new Article<>(Material.SUGAR_CANE, 100),
			new Article<>(Material.COCOA_BEANS, 100),
			new Article<>(Material.WHEAT_SEEDS, 100),
			new Article<>(Material.CARROT, 100),
			new Article<>(Material.POTATO, 100),
			new Article<>(Material.BEETROOT, 100),
			new Article<>(Material.PUMPKIN_SEEDS, 100),
			new Article<>(Material.MELON_SEEDS, 100),
			new Article<>(Material.RED_BED, 25),
			new Article<>(Material.TORCH, 5),
			new Article<>(Material.GLASS, 10),
			new Article<>(Material.GLASS_PANE, 10),
			new Article<>(Material.WHITE_WOOL, 10),
			new Article<>(Material.WHITE_CARPET, 10),
			new Article<>(Material.TERRACOTTA, 10),
			new Article<>(Material.WHITE_TERRACOTTA, 10),
			new Article<>(Material.ORANGE_TERRACOTTA, 10),
			new Article<>(Material.MAGENTA_TERRACOTTA, 10),
			new Article<>(Material.LIGHT_BLUE_TERRACOTTA, 10),
			new Article<>(Material.YELLOW_TERRACOTTA, 10),
			new Article<>(Material.LIME_TERRACOTTA, 10),
			new Article<>(Material.PINK_TERRACOTTA, 10),
			new Article<>(Material.GRAY_TERRACOTTA, 10),
			new Article<>(Material.LIGHT_GRAY_TERRACOTTA, 10),
			new Article<>(Material.CYAN_TERRACOTTA, 10),
			new Article<>(Material.PURPLE_TERRACOTTA, 10),
			new Article<>(Material.BLUE_TERRACOTTA, 10),
			new Article<>(Material.BROWN_TERRACOTTA, 10),
			new Article<>(Material.GREEN_TERRACOTTA, 10),
			new Article<>(Material.RED_TERRACOTTA, 10),
			new Article<>(Material.BLACK_TERRACOTTA, 10),
			new Article<>(Material.DIAMOND_SHOVEL, 100),
			new Article<>(Material.DIAMOND_PICKAXE, 100),
			new Article<>(Material.DIAMOND_AXE, 100),
			new Article<>(Material.DIAMOND_HOE, 100)
			);
	
	public CivilBlockShop() {
		super("blockshopcivil", null, DyeColor.CYAN, materials);
	}

}
